### ISSUE TITLE
Consider moving this repository to the https://github.com/dafny-lang organisation

### ISSUE THREAD

**Issue by keyboardDrummer** [DafnyVSCode/ide-vscode#36]
I think it'll make it easier to manage permissions and find this repository. Also, this repository serves as the reference client for https://github.com/dafny-lang/dafny/tree/master/Source/DafnyLanguageServer so I think it makes since if they're somehow grouped together.

Some documentation for moving a repository: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-organization

**Comment by camrein** [comment]
I'm sorry for the late reply. I'm currently on vacation and, therefore, slow to respond.
That sounds good to me, and I'll happily move it to the *dafny-lang* organization.

**Comment by keyboardDrummer** [comment]
> I'm sorry for the late reply.

No worries. 

Btw, I really like the code quality of the DafnyLanguageServer package. Thanks a lot of for that big contribution!

**Comment by camrein** [comment]
Thank you very much. I'm glad that you're happy with the code quality. You might have noticed that I've but several TODOs for cleanup. They're usually because my goal was to have the least possible influence on the compiler's code. But since they're now in the same repository, it makes sense to clean these up.
I'll now proceed with the transfer to the *dafny-lang* organization.
